# docker-compose.gpu.yml
version: '3.8'

services:
  dwsemdcmp:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]