# docker-compose.yml
version: '3.8'

services:
  dwsemdcmp:
    build: .
    container_name: dwsemdcmp_runner
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.azure:/root/.azure
    stdin_open: true
    tty: true